/**
 * Static EXPO_PUBLIC reads for React Native / Expo.
 * Metro only inlines `process.env.EXPO_PUBLIC_*` with literal property access —
 * dynamic `process.env[key]` is always undefined in the device bundle.
 */
export const expoPublicEnvBySuffix = {
  APPWRITE_ENDPOINT: process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT,
  APPWRITE_PROJECT_ID: process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID,
  APPWRITE_DATABASE_ID: process.env.EXPO_PUBLIC_APPWRITE_DATABASE_ID,
  APPWRITE_COLLECTION_TOURNAMENTS: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_TOURNAMENTS,
  APPWRITE_COLLECTION_PLAYERS: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_PLAYERS,
  APPWRITE_COLLECTION_RATINGS: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_RATINGS,
  APPWRITE_COLLECTION_CASUAL_MATCHES: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_CASUAL_MATCHES,
  APPWRITE_COLLECTION_APP_META: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_APP_META,
  APPWRITE_COLLECTION_SESSION_STATE: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_SESSION_STATE,
  APPWRITE_BUCKET_PLAYER_PHOTOS: process.env.EXPO_PUBLIC_APPWRITE_BUCKET_PLAYER_PHOTOS,
  APPWRITE_COLLECTION_V2_PLAYERS: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_V2_PLAYERS,
  APPWRITE_COLLECTION_V2_TOURNAMENTS: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_V2_TOURNAMENTS,
  APPWRITE_COLLECTION_V2_TOURNAMENT_TEAMS: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_V2_TOURNAMENT_TEAMS,
  APPWRITE_COLLECTION_V2_MATCHES: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_V2_MATCHES,
  APPWRITE_COLLECTION_V2_MATCH_PLAYERS: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_V2_MATCH_PLAYERS,
  APPWRITE_COLLECTION_V2_RATINGS_CURRENT: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_V2_RATINGS_CURRENT,
  APPWRITE_COLLECTION_GROUPS: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_GROUPS,
  APPWRITE_COLLECTION_GROUP_MEMBERS: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_GROUP_MEMBERS,
  APPWRITE_COLLECTION_GROUP_INVITES: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_GROUP_INVITES,
  APPWRITE_COLLECTION_GROUP_JOIN_REQUESTS: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_GROUP_JOIN_REQUESTS,
  APPWRITE_COLLECTION_GROUP_ACTIVE_LOCKS: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_GROUP_ACTIVE_LOCKS,
  APPWRITE_COLLECTION_TOURNAMENT_TEMPLATES: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_TOURNAMENT_TEMPLATES,
  APPWRITE_COLLECTION_GROUP_ROSTER: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_GROUP_ROSTER,
  APPWRITE_TOURNAMENT_DELETE_MODE: process.env.EXPO_PUBLIC_APPWRITE_TOURNAMENT_DELETE_MODE,
  GROUPS_ENABLED: process.env.EXPO_PUBLIC_GROUPS_ENABLED,
};
