import { buildPlayerAchievements } from '../utils/playerAchievements';
import { detectNewlyUnlockedBadges } from '@fixture-maker/domain/narrative';
import { matchesTournamentId } from '../utils/appHelpers';
import { useFixtureActions } from './tournament/useFixtureActions';
import { useScoringActions } from './tournament/useScoringActions';
import { useTournamentPersistence } from './tournament/useTournamentPersistence';
import { useTournamentHistory } from './tournament/useTournamentHistory';
import { useCasualMatchActions } from './tournament/useCasualMatchActions';
import { createSwapTeamMember } from './tournament/createSwapTeamMember';

export { useFixtureActions } from './tournament/useFixtureActions';
export { useScoringActions } from './tournament/useScoringActions';
export { useTournamentPersistence } from './tournament/useTournamentPersistence';
export { useTournamentHistory } from './tournament/useTournamentHistory';
export { useCasualMatchActions } from './tournament/useCasualMatchActions';

export const useTournamentActions = ({
  assertCanOperate,
  assertCanDelete,
  confirmAction,
  showToast,
  isAppwriteEnabled,
  activeGroup,
  queryClient = null,
  updatePlayerDatabase,
  tournamentName,
  setTournamentName,
  setNumTeams,
  format,
  gameMode,
  sportId,
  ruleConfig = {},
  tournamentFormat,
  setStep,
  setLoading,
  teams,
  setTeams,
  fixtures,
  setFixtures,
  bracket,
  setBracket,
  champion,
  setChampion,
  setPlayerDatabase,
  members,
  playerRatings,
  setPlayerRatings,
  tournamentHistory,
  setTournamentHistory,
  casualMatches,
  setCasualMatches,
  setShowCasualMatch,
  onCasualFlowComplete,
  aiMatchSummaries,
  setAiMatchSummaries,
  swapHistory,
  setSwapHistory,
  currentTournamentId,
  setCurrentTournamentId,
  setActiveTournamentLock,
  syncCurrentTournament,
  patchTournamentMatches,
  saveTournamentTransactionToAppwrite,
  markRatingsPersisted,
  buildRatingsDelta,
  saveTournamentMutation,
  deleteTournamentMutation,
  saveRatingsMutation,
  savePlayerDatabaseMutation,
  createCasualMatchMutation,
  deleteCasualMatchMutation,
}) => {
  const persistence = useTournamentPersistence({
    isAppwriteEnabled,
    activeGroup,
    tournamentName,
    format,
    gameMode,
    sportId,
    ruleConfig,
    tournamentFormat,
    teams,
    fixtures,
    bracket,
    champion,
    aiMatchSummaries,
    swapHistory,
    currentTournamentId,
    setCurrentTournamentId,
    tournamentHistory,
    setTournamentHistory,
    setActiveTournamentLock,
    syncCurrentTournament,
    patchTournamentMatches,
    saveTournamentMutation,
    buildRatingsDelta,
  });

  const getPlayersFromMatch = (match) => {
    if (!match?.team1 || !match?.team2) return [];
    const players = [
      match.team1.player || match.team1.player1,
      match.team1.player2,
      match.team2.player || match.team2.player1,
      match.team2.player2,
    ].filter(Boolean);
    return [...new Set(players)];
  };

  const getBadgeUnlocksForMatch = ({
    match,
    ratingsBefore,
    ratingsAfter,
    historyBefore = tournamentHistory,
    historyAfter = tournamentHistory,
  }) => {
    const players = getPlayersFromMatch(match);
    return players.flatMap((playerName) => {
      const before = buildPlayerAchievements({
        playerName,
        playerRatings: ratingsBefore,
        tournamentHistory: historyBefore,
        casualMatches,
      });
      const after = buildPlayerAchievements({
        playerName,
        playerRatings: ratingsAfter,
        tournamentHistory: historyAfter,
        casualMatches,
      });
      return detectNewlyUnlockedBadges(before.badges, after.badges).map((badge) => ({
        player: playerName,
        ...badge,
      }));
    });
  };

  const pushAiSummary = (summary) => {
    if (!summary) return aiMatchSummaries;
    const updated = [summary, ...aiMatchSummaries].slice(0, 50);
    setAiMatchSummaries(updated);
    return updated;
  };

  const {
    handleStartTournament,
    generateFixtures,
    scheduleTournament,
  } = useFixtureActions({
    assertCanOperate,
    showToast,
    isAppwriteEnabled,
    tournamentName,
    tournamentFormat,
    format,
    gameMode,
    sportId,
    ruleConfig,
    teams,
    playerRatings,
    tournamentHistory,
    setNumTeams,
    setStep,
    setLoading,
    setFixtures,
    setBracket,
    setPlayerRatings,
    setAiMatchSummaries,
    setSwapHistory,
    setCurrentTournamentId,
    setTournamentHistory,
    updatePlayerDatabase,
    saveTournamentMutation,
    deleteTournamentMutation,
    createTournamentRunIdRef: persistence.createTournamentRunIdRef,
    pendingCreateRef: persistence.pendingCreateRef,
    localTournamentIdRef: persistence.localTournamentIdRef,
    cloudIdWarningShownRef: persistence.cloudIdWarningShownRef,
    cloudIdRecoveryInFlightRef: persistence.cloudIdRecoveryInFlightRef,
    normalizeTournamentId: persistence.normalizeTournamentId,
    createLocalTournamentId: persistence.createLocalTournamentId,
    matchesTournamentId,
    upsertTournamentHistory: persistence.upsertTournamentHistory,
    persistActiveTournamentCache: persistence.persistActiveTournamentCache,
    updateActiveTournamentLock: persistence.updateActiveTournamentLock,
    clearActiveTournamentLockIfMatches: persistence.clearActiveTournamentLockIfMatches,
    resolveSyncTournamentIdForWrite: persistence.resolveSyncTournamentIdForWrite,
    buildActiveTournamentSnapshot: persistence.buildActiveTournamentSnapshot,
  });

  const {
    saveMatchResult,
    prioritizeMatch,
    updateMatchSchedule,
    saveBracketMatchResult,
    saveFinalResult,
    saveTournamentHistory,
  } = useScoringActions({
    assertCanOperate,
    showToast,
    isAppwriteEnabled,
    tournamentName,
    tournamentFormat,
    format,
    gameMode,
    sportId,
    ruleConfig,
    teams,
    fixtures,
    bracket,
    champion,
    swapHistory,
    playerRatings,
    tournamentHistory,
    casualMatches,
    aiMatchSummaries,
    currentTournamentId,
    setFixtures,
    setBracket,
    setChampion,
    setPlayerRatings,
    setAiMatchSummaries,
    setCurrentTournamentId,
    setTournamentHistory,
    setActiveTournamentLock,
    saveTournamentTransactionToAppwrite,
    markRatingsPersisted,
    ensureLocalTournamentId: persistence.ensureLocalTournamentId,
    resolveSyncTournamentId: persistence.resolveSyncTournamentId,
    resolveSyncTournamentIdForWrite: persistence.resolveSyncTournamentIdForWrite,
    getChangedLeagueMatchPatches: persistence.getChangedLeagueMatchPatches,
    getChangedBracketMatchPatches: persistence.getChangedBracketMatchPatches,
    patchTournamentMatchesWithFallback: persistence.patchTournamentMatchesWithFallback,
    recoverCloudTournamentIdInBackground: persistence.recoverCloudTournamentIdInBackground,
    buildActiveTournamentSnapshot: persistence.buildActiveTournamentSnapshot,
    buildCloudSyncPayload: persistence.buildCloudSyncPayload,
    buildRatingsDeltaPayload: persistence.buildRatingsDeltaPayload,
    getBadgeUnlocksForMatch,
    pushAiSummary,
    persistActiveTournamentSnapshot: persistence.persistActiveTournamentSnapshot,
    persistActiveTournamentCache: persistence.persistActiveTournamentCache,
    queueTournamentSync: persistence.queueTournamentSync,
    updateActiveTournamentLock: persistence.updateActiveTournamentLock,
    upsertTournamentHistory: persistence.upsertTournamentHistory,
    setRemoteActiveCache: persistence.setRemoteActiveCache,
    cloudIdWarningShownRef: persistence.cloudIdWarningShownRef,
    cloudIdRecoveryInFlightRef: persistence.cloudIdRecoveryInFlightRef,
    normalizeTournamentId: persistence.normalizeTournamentId,
    isLikelyLocalTournamentId: persistence.isLikelyLocalTournamentId,
    localTournamentIdRef: persistence.localTournamentIdRef,
    saveTournamentMutation,
    clearActiveTournamentCache: persistence.clearActiveTournamentCache,
    clearActiveTournamentLockIfMatches: persistence.clearActiveTournamentLockIfMatches,
  });

  const {
    rebuildPlayerDatabase,
    recalculateEloFromHistory,
    resetTournament,
    rerunTournament,
    goHome,
    startNextTournament,
    handleDeleteTournamentFromSetup,
  } = useTournamentHistory({
    assertCanOperate,
    assertCanDelete,
    confirmAction,
    showToast,
    isAppwriteEnabled,
    activeGroup,
    tournamentName,
    setTournamentName,
    setNumTeams,
    format,
    gameMode,
    sportId,
    ruleConfig,
    tournamentFormat,
    setStep,
    setTeams,
    setFixtures,
    setBracket,
    setChampion,
    setAiMatchSummaries,
    setSwapHistory,
    setCurrentTournamentId,
    setActiveTournamentLock,
    setPlayerDatabase,
    setPlayerRatings,
    members,
    playerRatings,
    tournamentHistory,
    setTournamentHistory,
    casualMatches,
    currentTournamentId,
    teams,
    fixtures,
    bracket,
    champion,
    generateFixtures,
    savePlayerDatabaseMutation,
    deleteTournamentMutation,
    saveRatingsMutation,
    buildRatingsDelta,
    markRatingsPersisted,
    normalizeTournamentId: persistence.normalizeTournamentId,
    isIdlessActiveTournamentNameMatch: persistence.isIdlessActiveTournamentNameMatch,
    clearActiveTournamentCache: persistence.clearActiveTournamentCache,
    fetchRemoteActiveLiveTournament: persistence.fetchRemoteActiveLiveTournament,
    clearActiveTournamentLockIfMatches: persistence.clearActiveTournamentLockIfMatches,
    createTournamentRunIdRef: persistence.createTournamentRunIdRef,
    localTournamentIdRef: persistence.localTournamentIdRef,
    pendingTournamentSyncRef: persistence.pendingTournamentSyncRef,
    tournamentSyncTimerRef: persistence.tournamentSyncTimerRef,
    cloudIdWarningShownRef: persistence.cloudIdWarningShownRef,
  });

  const {
    saveCasualMatch,
    handleDeleteCasualMatchFromSetup,
  } = useCasualMatchActions({
    assertCanOperate,
    assertCanDelete,
    confirmAction,
    showToast,
    isAppwriteEnabled,
    activeGroupId: activeGroup?.id || null,
    queryClient,
    playerRatings,
    setPlayerRatings,
    tournamentHistory,
    casualMatches,
    setCasualMatches,
    setShowCasualMatch,
    onCasualFlowComplete,
    createCasualMatchMutation,
    deleteCasualMatchMutation,
    rebuildPlayerDatabase,
    recalculateEloFromHistory,
  });

  const swapTeamMember = createSwapTeamMember({
    assertCanOperate,
    showToast,
    isAppwriteEnabled,
    teams,
    fixtures,
    bracket,
    champion,
    swapHistory,
    playerRatings,
    aiMatchSummaries,
    currentTournamentId,
    setTeams,
    setFixtures,
    setBracket,
    setPlayerRatings,
    setSwapHistory,
    setCurrentTournamentId,
    updatePlayerDatabase,
    persistActiveTournamentSnapshot: persistence.persistActiveTournamentSnapshot,
    resolveSyncTournamentId: persistence.resolveSyncTournamentId,
    buildActiveTournamentSnapshot: persistence.buildActiveTournamentSnapshot,
    queueTournamentSync: persistence.queueTournamentSync,
    updateActiveTournamentLock: persistence.updateActiveTournamentLock,
    casualMatches,
    tournamentHistory,
  });

  return {
    handleStartTournament,
    generateFixtures,
    scheduleTournament,
    saveMatchResult,
    prioritizeMatch,
    updateMatchSchedule,
    saveBracketMatchResult,
    saveFinalResult,
    saveTournamentHistory,
    saveCasualMatch,
    swapTeamMember,
    resetTournament,
    rerunTournament,
    startNextTournament,
    goHome,
    handleDeleteTournamentFromSetup,
    handleDeleteCasualMatchFromSetup,
  };
};
