const DEFAULT_GROUP_ID = 'default-group';
const PAGE_SIZE = 100;
const IN_QUERY_LIMIT = 100;
const PLAYER_LOOKUP_CACHE_TTL_MS = 60 * 1000;
const CHILD_CACHE_TTL_MS = 2 * 60 * 1000;
const TOURNAMENT_DELETED_STATUS = 'deleted';
const TOURNAMENT_DELETE_MODE = String(
  import.meta.env.VITE_APPWRITE_TOURNAMENT_DELETE_MODE || 'soft'
).trim().toLowerCase();

export {
  DEFAULT_GROUP_ID,
  PAGE_SIZE,
  IN_QUERY_LIMIT,
  PLAYER_LOOKUP_CACHE_TTL_MS,
  CHILD_CACHE_TTL_MS,
  TOURNAMENT_DELETED_STATUS,
  TOURNAMENT_DELETE_MODE,
};
