const readEnv = (key) => import.meta.env[key];

export const APPWRITE_ENDPOINT = readEnv('VITE_APPWRITE_ENDPOINT') || 'https://nyc.cloud.appwrite.io/v1';
export const APPWRITE_PROJECT_ID = readEnv('VITE_APPWRITE_PROJECT_ID');
export const APPWRITE_DATABASE_ID = readEnv('VITE_APPWRITE_DATABASE_ID');

export const COLLECTIONS = {
  TOURNAMENTS: readEnv('VITE_APPWRITE_COLLECTION_TOURNAMENTS'),
  PLAYERS: readEnv('VITE_APPWRITE_COLLECTION_PLAYERS'),
  RATINGS: readEnv('VITE_APPWRITE_COLLECTION_RATINGS'),
  CASUAL_MATCHES: readEnv('VITE_APPWRITE_COLLECTION_CASUAL_MATCHES'),
  APP_META: readEnv('VITE_APPWRITE_COLLECTION_APP_META') || '',

  TOURNAMENTS_V2: readEnv('VITE_APPWRITE_COLLECTION_V2_TOURNAMENTS') || '',
  TOURNAMENT_TEAMS_V2: readEnv('VITE_APPWRITE_COLLECTION_V2_TOURNAMENT_TEAMS') || '',
  MATCHES_V2: readEnv('VITE_APPWRITE_COLLECTION_V2_MATCHES') || '',
  MATCH_PLAYERS_V2: readEnv('VITE_APPWRITE_COLLECTION_V2_MATCH_PLAYERS') || '',
  PLAYERS_V2: readEnv('VITE_APPWRITE_COLLECTION_V2_PLAYERS') || '',
  RATINGS_CURRENT_V2: readEnv('VITE_APPWRITE_COLLECTION_V2_RATINGS_CURRENT') || '',

  GROUPS: readEnv('VITE_APPWRITE_COLLECTION_GROUPS') || '',
  GROUP_MEMBERS: readEnv('VITE_APPWRITE_COLLECTION_GROUP_MEMBERS') || '',
  GROUP_INVITES: readEnv('VITE_APPWRITE_COLLECTION_GROUP_INVITES') || '',
  GROUP_JOIN_REQUESTS: readEnv('VITE_APPWRITE_COLLECTION_GROUP_JOIN_REQUESTS') || '',
  GROUP_ACTIVE_LOCKS: readEnv('VITE_APPWRITE_COLLECTION_GROUP_ACTIVE_LOCKS') || '',

  TOURNAMENT_TEMPLATES: readEnv('VITE_APPWRITE_COLLECTION_TOURNAMENT_TEMPLATES') || '',
  GROUP_ROSTER: readEnv('VITE_APPWRITE_COLLECTION_GROUP_ROSTER') || '',
};

export const BUCKETS = {
  PLAYER_PHOTOS: readEnv('VITE_APPWRITE_BUCKET_PLAYER_PHOTOS') || '',
};

export const isAppwriteConfigured = () => Boolean(
  APPWRITE_PROJECT_ID
  && APPWRITE_DATABASE_ID
  && COLLECTIONS.TOURNAMENTS_V2
  && COLLECTIONS.TOURNAMENT_TEAMS_V2
  && COLLECTIONS.MATCHES_V2
  && COLLECTIONS.MATCH_PLAYERS_V2
  && COLLECTIONS.PLAYERS_V2
  && COLLECTIONS.RATINGS_CURRENT_V2
);
